<?php

namespace App\Http\Controllers;

use App\Core\Utils;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Core\TatucoController;
use App\Http\Services\EventTypeService;

class EventTypeController extends TatucoController
{
    public function __construct()
    {
        parent::__construct(new EventTypeService());
    }

    public function index(Request $request)
    {
        //$where = '[["op" => "gt", "field" => "id", "value" => 1]]';
      //  if($request->has("where")) {
        //    $arr_where = Utils::parseWhere($request->where);

       //     array_push($where, $arr_where);
       // }
      //  $request->merge(["where" => $where]);
        //print_r($where);
        return parent::index($request); // TODO: Change the autogenerated stub
    }
    /*public function select(Request $request)
    {
        $where = [
            ["op" => "gt", "field" => "id", "value" => 1]
        ];
        $request->merge(['where' => $where]);
        return $request;
        return parent::select($request);
    }*/
}
